/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule SensorChartRefetchQuery.graphql
 * @generated SignedSource<<583f4b39541bfbd9ffbe450acf04ff6c>>
 * @relayHash 1be8d2965da3003c7777176a70d35a35
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';

*/


/*
query SensorChartRefetchQuery(
  $sid: ID!
) {
  sensor(id: $sid) {
    ...SensorChart_sensor
    id
  }
}

fragment SensorChart_sensor on Sensor {
  trueid
  name
  sensordata {
    val
    time
  }
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [
      {
        "kind": "LocalArgument",
        "name": "sid",
        "type": "ID!",
        "defaultValue": null
      }
    ],
    "kind": "Fragment",
    "metadata": null,
    "name": "SensorChartRefetchQuery",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": [
          {
            "kind": "Variable",
            "name": "id",
            "variableName": "sid",
            "type": "ID!"
          }
        ],
        "concreteType": "Sensor",
        "name": "sensor",
        "plural": false,
        "selections": [
          {
            "kind": "FragmentSpread",
            "name": "SensorChart_sensor",
            "args": null
          }
        ],
        "storageKey": null
      }
    ],
    "type": "Query"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "SensorChartRefetchQuery",
  "query": {
    "argumentDefinitions": [
      {
        "kind": "LocalArgument",
        "name": "sid",
        "type": "ID!",
        "defaultValue": null
      }
    ],
    "kind": "Root",
    "name": "SensorChartRefetchQuery",
    "operation": "query",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": [
          {
            "kind": "Variable",
            "name": "id",
            "variableName": "sid",
            "type": "ID!"
          }
        ],
        "concreteType": "Sensor",
        "name": "sensor",
        "plural": false,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "trueid",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "name",
            "storageKey": null
          },
          {
            "kind": "LinkedField",
            "alias": null,
            "args": null,
            "concreteType": "SensorData",
            "name": "sensordata",
            "plural": true,
            "selections": [
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "val",
                "storageKey": null
              },
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "time",
                "storageKey": null
              }
            ],
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "id",
            "storageKey": null
          }
        ],
        "storageKey": null
      }
    ]
  },
  "text": "query SensorChartRefetchQuery(\n  $sid: ID!\n) {\n  sensor(id: $sid) {\n    ...SensorChart_sensor\n    id\n  }\n}\n\nfragment SensorChart_sensor on Sensor {\n  trueid\n  name\n  sensordata {\n    val\n    time\n  }\n}\n"
};

module.exports = batch;
