/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule SensorChart_sensor.graphql
 * @generated SignedSource<<c5ef18d8c8b21379a499cc8ba3cf38df>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type SensorChart_sensor = {|
  +trueid: number;
  +name: string;
  +sensordata: ?$ReadOnlyArray<?{|
    +val: number;
    +time: number;
  |}>;
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "SensorChart_sensor",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "trueid",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "name",
      "storageKey": null
    },
    {
      "kind": "LinkedField",
      "alias": null,
      "args": null,
      "concreteType": "SensorData",
      "name": "sensordata",
      "plural": true,
      "selections": [
        {
          "kind": "ScalarField",
          "alias": null,
          "args": null,
          "name": "val",
          "storageKey": null
        },
        {
          "kind": "ScalarField",
          "alias": null,
          "args": null,
          "name": "time",
          "storageKey": null
        }
      ],
      "storageKey": null
    }
  ],
  "type": "Sensor"
};

module.exports = fragment;
