/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule SensorChart_sensordata.graphql
 * @generated SignedSource<<9750157d13030313f89d0648ea02c4f1>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type SensorChart_sensordata = {|
  +val: number;
  +time: number;
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": {
    "plural": true
  },
  "name": "SensorChart_sensordata",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "val",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "time",
      "storageKey": null
    }
  ],
  "type": "SensorData"
};

module.exports = fragment;
