/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule InvokedRuleCardQuery.graphql
 * @generated SignedSource<<fce21df0d68eab7a4f3a48f8bda4ed17>>
 * @relayHash 201ad708ff8bf102b9aeb76418fe223e
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';

*/


/*
query InvokedRuleCardQuery(
  $id: ID!
) {
  invokedRules(ruleid: $id) {
    id
    rulename
    data
    time
  }
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [
      {
        "kind": "LocalArgument",
        "name": "id",
        "type": "ID!",
        "defaultValue": null
      }
    ],
    "kind": "Fragment",
    "metadata": null,
    "name": "InvokedRuleCardQuery",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": [
          {
            "kind": "Variable",
            "name": "ruleid",
            "variableName": "id",
            "type": "ID!"
          }
        ],
        "concreteType": "InvokedRule",
        "name": "invokedRules",
        "plural": true,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "id",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "rulename",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "data",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "time",
            "storageKey": null
          }
        ],
        "storageKey": null
      }
    ],
    "type": "Query"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "InvokedRuleCardQuery",
  "query": {
    "argumentDefinitions": [
      {
        "kind": "LocalArgument",
        "name": "id",
        "type": "ID!",
        "defaultValue": null
      }
    ],
    "kind": "Root",
    "name": "InvokedRuleCardQuery",
    "operation": "query",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": [
          {
            "kind": "Variable",
            "name": "ruleid",
            "variableName": "id",
            "type": "ID!"
          }
        ],
        "concreteType": "InvokedRule",
        "name": "invokedRules",
        "plural": true,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "id",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "rulename",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "data",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "time",
            "storageKey": null
          }
        ],
        "storageKey": null
      }
    ]
  },
  "text": "query InvokedRuleCardQuery(\n  $id: ID!\n) {\n  invokedRules(ruleid: $id) {\n    id\n    rulename\n    data\n    time\n  }\n}\n"
};

module.exports = batch;
