/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule SensorCard_sensors.graphql
 * @generated SignedSource<<5dca23b5dc4dfe0a53092badfdeb8e5a>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type SensorCard_sensors = {|
  +id: string;
  +trueid: number;
  +name: string;
  +sensordata: ?$ReadOnlyArray<?{| |}>;
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": {
    "plural": true
  },
  "name": "SensorCard_sensors",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "id",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "trueid",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "name",
      "storageKey": null
    },
    {
      "kind": "LinkedField",
      "alias": null,
      "args": null,
      "concreteType": "SensorData",
      "name": "sensordata",
      "plural": true,
      "selections": [
        {
          "kind": "FragmentSpread",
          "name": "SensorChart_sensordata",
          "args": null
        }
      ],
      "storageKey": null
    }
  ],
  "type": "Sensor"
};

module.exports = fragment;
