/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule RuleModalQuery.graphql
 * @generated SignedSource<<200241e2508f7e29c37618919148649f>>
 * @relayHash 928c30d7c6266441183913ccecdb7c49
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';

*/

/* eslint-disable comma-dangle, quotes */

/*
query RuleModalQuery {
  sensors {
    ...RuleForm_sensors
    id
  }
  actions {
    ...RuleForm_actions
    id
  }
}

fragment RuleForm_sensors on Sensor {
  id
  trueid
  name
}

fragment RuleForm_actions on Action {
  id
  name
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [],
    "kind": "Fragment",
    "metadata": null,
    "name": "RuleModalQuery",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "Sensor",
        "name": "sensors",
        "plural": true,
        "selections": [
          {
            "kind": "FragmentSpread",
            "name": "RuleForm_sensors",
            "args": null
          }
        ],
        "storageKey": null
      },
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "Action",
        "name": "actions",
        "plural": true,
        "selections": [
          {
            "kind": "FragmentSpread",
            "name": "RuleForm_actions",
            "args": null
          }
        ],
        "storageKey": null
      }
    ],
    "type": "Query"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "RuleModalQuery",
  "query": {
    "argumentDefinitions": [],
    "kind": "Root",
    "name": "RuleModalQuery",
    "operation": "query",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "Sensor",
        "name": "sensors",
        "plural": true,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "id",
            "storageKey": null
          },
          {
            "kind": "InlineFragment",
            "type": "Sensor",
            "selections": [
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "trueid",
                "storageKey": null
              },
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "name",
                "storageKey": null
              }
            ]
          }
        ],
        "storageKey": null
      },
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "Action",
        "name": "actions",
        "plural": true,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "id",
            "storageKey": null
          },
          {
            "kind": "InlineFragment",
            "type": "Action",
            "selections": [
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "name",
                "storageKey": null
              }
            ]
          }
        ],
        "storageKey": null
      }
    ]
  },
  "text": "query RuleModalQuery {\n  sensors {\n    ...RuleForm_sensors\n    id\n  }\n  actions {\n    ...RuleForm_actions\n    id\n  }\n}\n\nfragment RuleForm_sensors on Sensor {\n  id\n  trueid\n  name\n}\n\nfragment RuleForm_actions on Action {\n  id\n  name\n}\n"
};

module.exports = batch;
