/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule DashboardQuery.graphql
 * @generated SignedSource<<214fabf93fd7a7ef216ad91bf8dbae38>>
 * @relayHash 332a1ed85f9d150a329e5e6ae971f596
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';

*/

/* eslint-disable comma-dangle, quotes */

/*
query DashboardQuery {
  sensors {
    ...SensorCard_sensors
    id
  }
  rules {
    ...RuleCard_rules
    id
  }
}

fragment SensorCard_sensors on Sensor {
  id
  name
  connection
  status
  type
}

fragment RuleCard_rules on Rule {
  id
  name
  index
  status
  rule
  actionID
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [],
    "kind": "Fragment",
    "metadata": null,
    "name": "DashboardQuery",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "Sensor",
        "name": "sensors",
        "plural": true,
        "selections": [
          {
            "kind": "FragmentSpread",
            "name": "SensorCard_sensors",
            "args": null
          }
        ],
        "storageKey": null
      },
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "Rule",
        "name": "rules",
        "plural": true,
        "selections": [
          {
            "kind": "FragmentSpread",
            "name": "RuleCard_rules",
            "args": null
          }
        ],
        "storageKey": null
      }
    ],
    "type": "Query"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "DashboardQuery",
  "query": {
    "argumentDefinitions": [],
    "kind": "Root",
    "name": "DashboardQuery",
    "operation": "query",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "Sensor",
        "name": "sensors",
        "plural": true,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "id",
            "storageKey": null
          },
          {
            "kind": "InlineFragment",
            "type": "Sensor",
            "selections": [
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "name",
                "storageKey": null
              },
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "connection",
                "storageKey": null
              },
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "status",
                "storageKey": null
              },
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "type",
                "storageKey": null
              }
            ]
          }
        ],
        "storageKey": null
      },
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "Rule",
        "name": "rules",
        "plural": true,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "id",
            "storageKey": null
          },
          {
            "kind": "InlineFragment",
            "type": "Rule",
            "selections": [
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "name",
                "storageKey": null
              },
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "index",
                "storageKey": null
              },
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "status",
                "storageKey": null
              },
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "rule",
                "storageKey": null
              },
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "actionID",
                "storageKey": null
              }
            ]
          }
        ],
        "storageKey": null
      }
    ]
  },
  "text": "query DashboardQuery {\n  sensors {\n    ...SensorCard_sensors\n    id\n  }\n  rules {\n    ...RuleCard_rules\n    id\n  }\n}\n\nfragment SensorCard_sensors on Sensor {\n  id\n  name\n  connection\n  status\n  type\n}\n\nfragment RuleCard_rules on Rule {\n  id\n  name\n  index\n  status\n  rule\n  actionID\n}\n"
};

module.exports = batch;
